Update _base.py
Pydantic v2 中适配字段名和字段别名的方式，原始方式
    model_config = ConfigDict(
        # SEE: https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.populate_by_name
        validate_by_name=True,
        validate_by_alias=True,
        serialize_by_alias=True,
        alias_generator=to_camel_custom,
    )
会导致  实例化 AgentCard 方法的时候 报错
pydantic_core._pydantic_core.ValidationError: 2 validation errors for AgentCard
defaultInputModes
  Field required [type=missing, input_value={'name': 'Hello World Age...ed_extended_card': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
defaultOutputModes